apiVersion: v1
kind: Namespace
metadata:
  name: argocd
  labels:
    app.kubernetes.io/managed-by: kustomize
---
apiVersion: v1
kind: Namespace
metadata:
  name: vault
  labels:
    app.kubernetes.io/managed-by: kustomize
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: falco
  labels:
    app.kubernetes.io/managed-by: kustomize
---
apiVersion: v1
kind: Namespace
metadata:
  name: gatekeeper-system
  labels:
    app.kubernetes.io/managed-by: kustomize
---
apiVersion: v1
kind: Namespace
metadata:
  name: kyverno
  labels:
    app.kubernetes.io/managed-by: kustomize
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    app.kubernetes.io/managed-by: kustomize
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  labels:
    app.kubernetes.io/managed-by: kustomize
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    app.kubernetes.io/managed-by: kustomize
---
apiVersion: v1
kind: Namespace
metadata:
  name: secure-apps
  labels:
    app.kubernetes.io/managed-by: kustomize
    istio-injection: enabled
    environment: production
